version: "3"

services:
  db-mysql:
    image: mysql:8.0.23
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - atividade2

  backend:
    build: .
    image: atividade
    environment:
      MYSQL_HOST: db-mysql
      MYSQL_USERNAME: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DB: ${DB_DATABASE}
    ports:
      - "8080:8080"
    depends_on:
      - db-mysql
    networks:
      - atividade2
    volumes:
      - mysql-volume:/var/lib/mysql/data

volumes:
  mysql-volume:

networks:
  atividade2:
    driver: bridge